const songs = [
    {
        title: "Bags",
        file: "media/bags.mp3",
        artist: "Clairo",
        img: "media/valentines.jpeg",
        lyrics: "Can you see me? I'm waiting for the right time. I can't read you, but if you want, the pleasure's all mine",
    },
    {
        title: "Dos Oruguitas",
        file: "media/dosoruguitas.mp3",
        artist: "Sebastian Yatra",
        img: "media/vintage.JPG",
        lyrics: "Dos oruguitas enamoradas, pasan sus noches y madrugadas. Llenas de hambre, siguen andando y navegando un mundo que cambia y sigue cambiando",
    },
    {
        title: "Call Me Up",
        file: "media/callmeup.mp3",
        artist: "Daydreamers",
        img: "media/yellow.jpeg",
        lyrics: "If you get low and you're needin' my touch, you can call me up, honey, you can call me up. If you need a rush, call me up, call me up",
    },
    {
        title: "Would That I",
        file: "media/wouldthati.mp3",
        artist: "Hozier",
        img: "media/meet.jpeg",
        lyrics: "And it's not tonight Where I'm set alight, and I blink in sight Of your blinding light",
    },
    {
        title: "The Sound",
        file: "media/thesound.mp3",
        artist: "The 1975",
        img: "media/motmot.JPG",
        lyrics: "Well, I know when you're around 'Cause I know the sound, I know the sound of your heart",
    },
    {
        title: "Pangarap Lang Kita",
        file: "media/pangaraplangkita.mp3",
        artist: "Parokya ni Edgar",
        img: "media/cny.jpeg",
        lyrics: "At kahit mahal kita, Wala akong magagawa. Tanggap ko, oh, aking sinta. Pangarap lang kita",
    },
    {
        title: "Everything Has Changed",
        file: "media/everythinghaschanged.mp3",
        artist: "Taylor Swift",
        img: "media/first.jpeg",
        lyrics: "All I know is you held the door You'll be mine and I'll be yours All I know since yesterday Is everything has changed",
    },
    {
        title: "Someone To You",
        file: "media/someonetoyou.mp3",
        artist: "Banners",
        img: "media/hp.jpeg",
        lyrics: "I don't even need to change the world. I'll make the moon shine just for your view, I'll make the starlight circle the room",
    },
    {
        title: "Lover Girl",
        file: "media/lovergirl.mp3",
        artist: "Laufey",
        img: "media/concert.jpeg",
        lyrics: "You've been hosting parties in my mind, I'm working overtime, You've become my whole world. Oh, what a curse it is to be a lover girl",
    },
    {
        title: "Bless The Telephone",
        file: "media/blessthetelephone.mp3",
        artist: "Labi Siffre",
        img: "media/train.jpeg",
        lyrics: "It's nice, the way you say my name Not very fast or slow, just soft and low The same as when you tell me how you feel I feel the same way, too I'm very much in love with you",
    },
];
