const songs = [
    {
        title: "Bags",
        file: "media/bags.mp3",
        artist: "Clairo",
        img: "/media/valentines.jpeg",
        lyrics: "Can you see me? I'm waiting for the right time. I can't read you, but if you want, the pleasure's all mine",
    },
    {
        title: "Our Song",
        file: "media/bags.m4a",
        artist: "Taylor Swift",
        img: "/media/vintage.JPG",
        lyrics: "Our song is the slamming screen door, sneakin' out late, tapping on your window. When we're on the phone, and you talk real slow.. 'Cause it's late and your momma don't know",
    },
    {
        title: "Call Me Up",
        file: "media/bags.m4a",
        artist: "Daydreamers",
        img: "/media/yellow.jpeg",
        lyrics: "If you get low and you're needin' my touch, you can call me up, honey, you can call me up. If you need a rush, call me up, call me up",
    },
    {
        title: "Would That I",
        file: "media/bags.m4a",
        artist: "Hozier",
        img: "/media/meet.jpeg",
        lyrics: "And it's not tonight Where I'm set alight, and I blink in sight Of your blinding light",
    },
    {
        title: "The Sound",
        file: "media/bags.m4a",
        artist: "The 1975",
        img: "/media/motmot.JPG",
        lyrics: "Well, I know when you're around 'Cause I know the sound, I know the sound of your heart",
    },
    {
        title: "Pangarap Lang Kita",
        file: "media/bags.m4a",
        artist: "Parokya ni Edgar",
        img: "/media/cny.jpeg",
        lyrics: "At kahit mahal kita, Wala akong magagawa. Tanggap ko, oh, aking sinta. Pangarap lang kita",
    },
    {
        title: "Everything Has Changed",
        file: "media/bags.m4a",
        artist: "Taylor Swift",
        img: "/media/first.jpeg",
        lyrics: "All I know is you held the door You'll be mine and I'll be yours All I know since yesterday Is everything has changed",
    },
    {
        title: "Someone To You",
        file: "media/bags.m4a",
        artist: "Banners",
        img: "/media/hp.jpeg",
        lyrics: "I don't even need to change the world. I'll make the moon shine just for your view, I'll make the starlight circle the room",
    },
    {
        title: "Lover Girl",
        file: "media/bags.m4a",
        artist: "Laufey",
        img: "/media/concert.jpeg",
        lyrics: "You've been hosting parties in my mind, I'm working overtime, You've become my whole world. Oh, what a curse it is to be a lover girl",
    },
    {
        title: "Bless The Telephone",
        file: "media/bags.m4a",
        artist: "Labi Siffre",
        img: "/media/train.jpeg",
        lyrics: "It's nice, the way you say my name Not very fast or slow, just soft and low The same as when you tell me how you feel I feel the same way, too I'm very much in love with you",
    },
];
